spring:
  jmx:
    enabled: false
  thymeleaf:
    cache: false
  mobile: 
    devicedelegatingviewresolver:
      enabled: true
      mobile-prefix: 
      tablet-prefix: 
      mobile-suffix: .mobile
      tablet-suffix: .mobile  #.tablet
      
  datasource:
    url: jdbc:mysql://localhost:3306/jiameng?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
    
mybatis:
  config: mybatis-config.xml
      
server:
  port: 9091
  tomcat:
    access-log-enabled: true
    basedir: target/tomcat 
  error:
    include-stacktrace: never
    path: /error
    whitelabel:
      enabled: true   
         
logging:
  level:
    com.jiayuan.bank: info
  file: /data/log/jingxuan.webmvc.log
resource: 
  upload-addr: 192.168.1.206:22
  upload-username: root
  upload-password: 1qaz2wsx
  download-addr: 192.168.1.206:80
  